### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by jayvdb** [steptr/MIT-License#1]
There does not appear to be a repo for translations.
http://softwareengineering.stackexchange.com/questions/75922/where-can-i-find-translations-of-osi-approved-licenses

Are you interested? I can organise at least a high quality Indonesian immediately, but I can ask Wikipedia editors which should result a few other languages like French and German very soon.

**Comment by steptr** [comment]
Thank you for your interest. You are welcome to link to this page from your project, or include the translated text directly under the Creative Commons Attribution-ShareAlike License CC-A-SA, see [README.md](https://github.com/steptr/MIT-license/blob/bcfd7b5038a772c309b78fe7bf3aae6c932d66ba/README.md).

**Comment by jayvdb** [comment]
Can we contribute new translations in other languages?  Or is it only Italian?

**Comment by steptr** [comment]
You can, on a trial basis, since this is the first time someone asks.
Be prepared to fix/amend your translation if other people report issues.

Steps:
- Verify that your English source is identical to [MIT_License-en.txt](https://github.com/steptr/MIT-License/commit/fd01238d2aea241c7840861c86f715887e23d6b6#diff-066fb78cd0d68d55f0fc960049b45857).
- Add a translation file named MIT_License-xx.txt for each language you wish to provide a translation, where xx is a the country code, which may also include a specific locale code, as per Linux `LANG` variable values. Use a valid Unicode encoding for your file(s) with UTF-8 as default.
- Add a descriptive section for each language to file README.md. Specify file encoding if other than UTF-8. Don't forget to specify translation authors.
- Submit a pull request.

**Comment by steptr** [comment]
You can, on a trial basis, since this is the first time someone asks.
Be prepared to fix/amend your translation if other people report issues.

Steps:
- Verify that your English source is identical to [MIT_License-en.txt](https://github.com/steptr/MIT-License/commit/fd01238d2aea241c7840861c86f715887e23d6b6#diff-066fb78cd0d68d55f0fc960049b45857).
- Add a translation file named MIT_License-xx.txt for each language you wish to provide a translation, where xx is a the country code, which may also include a specific locale code, as per Linux `LANG` variable values. Use a valid Unicode encoding for your file(s) with UTF-8 as default.
- Add a descriptive section for each language to file README.md. Specify file encoding if other than UTF-8. Don't forget to specify translation authors.
- Submit a pull request.

Thank you.

**Comment by steptr** [comment]
#2, #3, 98e47fa.
